// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efymqilxmoptnugkcset.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmeW1xaWx4bW9wdG51Z2tjc2V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNDA1NjUsImV4cCI6MjA2MTkxNjU2NX0.BYFzVC-W6tUrDfIrf_OBAPx1iHnI7_LXzJ1JZx3wddM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);